### ISSUE TITLE
如何处理因为网络或dns导致的连接失败?

### ISSUE THREAD

**Issue by Ben-Huang** [walkor/http-client#24]
环境:Workerman version:5.0.0-beta.7    PHP version:8.2.12     Event-loop:Workerman\Events\Revolt
目前当遇到网络波动或dns解析错误而连接失败时,无法处理错误,导致worker重启.

例子代码:
```
<?php
use Workerman\Worker;
use Workerman\Connection\AsyncTcpConnection;

require_once __DIR__ . '/vendor/autoload.php';

date_default_timezone_set( 'Asia/Shanghai' );
$worker = new Worker();
$worker->count = 1;
$worker->onWorkerStart = function($worker){
	
	$http = new \Workerman\Http\Client();
        $http->request('http://httpbin9.org/cookies', [
            'success' => function ($response) {
                echo $response->getBody();
            },
            'error' => function ($exception) {
                echo $exception;
            }
        ]);
       //or 协程用法
	try {
		$response = $http->request('http://httpbin9.org/cookies');
		echo $response->getBody();
	} catch (\Throwable $th) {
		var_dump('errrrr');
	}

};

Worker::runAll();
```

**Comment by walkor** [comment]
更新到2.1.4
url解析失败协程必须抛异常，异步调用不会抛出异常

**Comment by Ben-Huang** [comment]
更新到2.1.4后,协程用法依然无法处理错误, 
```
Workerman version:5.0.0-beta.7    PHP version:8.2.12     Event-loop:Workerman\Events\Revolt
----------------------------------------- WORKERS ------------------------------------------
proto   user            worker          listen          processes    state            
tcp     root            none            none            1             [OK]            
--------------------------------------------------------------------------------------------
Press Ctrl+C to stop. Start success.

Warning: stream_socket_client(): Unable to connect to tcp://httpbin9.org:80 (Socket connect failed, reason: DNS getaddrinfo failed, reason: Unknown node or service) in /upan/cli/dm/vendor/workerman/workerman/src/Connection/AsyncTcpConnection.php on line 286

Warning: stream_socket_client(): Unable to connect to tcp://httpbin9.org:80 (Socket connect failed, reason: DNS getaddrinfo failed, reason: Unknown node or service) in /upan/cli/dm/vendor/workerman/workerman/src/Connection/AsyncTcpConnection.php on line 286
Error: Must call suspend() before calling throw() in /upan/cli/dm/vendor/revolt/event-loop/src/EventLoop/Internal/DriverSuspension.php:159
Stack trace:
#0 /upan/cli/dm/vendor/workerman/http-client/src/Client.php(81): Revolt\EventLoop\Internal\DriverSuspension->throw(Object(Exception))
#1 [internal function]: Workerman\Http\Client->Workerman\Http\{closure}(Object(Exception))
#2 /upan/cli/dm/vendor/workerman/http-client/src/Client.php(221): call_user_func(Object(Closure), Object(Exception))
#3 [internal function]: Workerman\Http\Client->Workerman\Http\{closure}(Object(Exception))
#4 /upan/cli/dm/vendor/workerman/http-client/src/Emitter.php(120): call_user_func_array(Object(Closure), Array)
#5 [internal function]: Workerman\Http\Emitter->emit('error', Object(Exception))
#6 /upan/cli/dm/vendor/workerman/http-client/src/Request.php(141): call_user_func_array(Array, Array)
#7 /upan/cli/dm/vendor/workerman/http-client/src/Request.php(475): Workerman\Http\Request->emit('error', Object(Exception))
#8 /upan/cli/dm/vendor/workerman/http-client/src/Request.php(461): Workerman\Http\Request->emitError(Object(Exception))
#9 /upan/cli/dm/vendor/workerman/workerman/src/Connection/AsyncTcpConnection.php(325): Workerman\Http\Request->onError(Object(Workerman\Connection\AsyncTcpConnection), 1, 'Socket connect ...')
#10 /upan/cli/dm/vendor/workerman/workerman/src/Connection/AsyncTcpConnection.php(295): Workerman\Connection\AsyncTcpConnection->emitError(1, 'Socket connect ...')
#11 /upan/cli/dm/vendor/workerman/workerman/src/Connection/AsyncTcpConnection.php(236): Workerman\Connection\AsyncTcpConnection->connect()
#12 /upan/cli/dm/vendor/workerman/http-client/src/Client.php(233): Workerman\Connection\AsyncTcpConnection->reconnect()
#13 /upan/cli/dm/vendor/workerman/http-client/src/Client.php(85): Workerman\Http\Client->process('tcp://httpbin9....')
#14 /upan/cli/dm/tt.php(23): Workerman\Http\Client->request('http://httpbin9...')
#15 /upan/cli/dm/vendor/workerman/workerman/src/Worker.php(2443): {closure}(Object(Workerman\Worker))
#16 /upan/cli/dm/vendor/workerman/workerman/src/Worker.php(1592): Workerman\Worker->run()
#17 /upan/cli/dm/vendor/workerman/workerman/src/Worker.php(1394): Workerman\Worker::forkOneWorkerForLinux(Object(Workerman\Worker))
#18 /upan/cli/dm/vendor/workerman/workerman/src/Worker.php(1368): Workerman\Worker::forkWorkersForLinux()
#19 /upan/cli/dm/vendor/workerman/workerman/src/Worker.php(572): Workerman\Worker::forkWorkers()
#20 /upan/cli/dm/tt.php(31): Workerman\Worker::runAll()
#21 {main}
worker[none:448977] exit with status 64000

```

**Comment by walkor** [comment]
更新到2.1.5 试下
